name: Build and deploy

on:
  push:
    branches:
      - "*"
    tags:
      - v*
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: build dist
        run: |
          UPDATE_BINARY_URL="https://raw.githubusercontent.com/topjohnwu/Magisk/master/scripts/module_installer.sh"
          curl "${UPDATE_BINARY_URL}" > ./META-INF/com/google/android/update-binary
          echo "#MAGISK" > ./META-INF/com/google/android/updater-script
          VERSION=$(sed -ne "s/version=\(.*\)/\1/gp" ./module.prop)
          NAME=$(sed -ne "s/id=\(.*\)/\1/gp" ./module.prop)
          rm -f ${NAME}-${VERSION}.zip
          zip -r ${NAME}-${VERSION}.zip META-INF system module.prop post-fs-data.sh
          ls -la

      - name: create release
        uses: ncipollo/release-action@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          artifacts: "custom-certificates-*.zip"
          generateReleaseNotes: true

      - name: write PR url
        if: github.event_name == 'pull_request'
        run: |
          echo "${{ github.event.pull_request.html_url }}" > pull_request_url.txt

      - name: upload artifact
        uses: actions/upload-artifact@v3
        if: github.event_name == 'pull_request'
        with:
          name: custom certificates module build
          path: |
            custom-certificates-*.zip
            README.md
            pull_request_url.txt
